# Generated by Django 4.2.20 on 2025-03-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('scrape_date', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sizes', models.CharField(blank=True, max_length=255, null=True)),
                ('colors', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
