# Generated by Django 4.2.20 on 2025-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='original_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='special_price',
            new_name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scrape_date',
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
